-- ============================================================================
-- Migration: Chat System
-- Description: conversations, messages, chat_attachments tables with functions,
--              indexes, RLS policies, triggers, and grants
-- ============================================================================

-- ==========================================================
-- FUNCTIONS
-- ==========================================================

-- update_action_status: Updates the status field of an action within content_parts JSONB
CREATE OR REPLACE FUNCTION "public"."update_action_status"("p_message_id" "uuid", "p_action_id" "text", "p_status" "text") RETURNS "void"
    LANGUAGE "plpgsql"
    AS $$
DECLARE
    i INT;
    parts JSONB;
BEGIN
    -- Get current content_parts
    SELECT content_parts INTO parts FROM messages WHERE id = p_message_id;

    -- Return early if no content_parts
    IF parts IS NULL THEN
        RETURN;
    END IF;

    -- Loop through array and update matching action
    FOR i IN 0..jsonb_array_length(parts) - 1 LOOP
        IF parts->i->>'id' = p_action_id AND parts->i->>'type' = 'action' THEN
            parts = jsonb_set(
                parts,
                ARRAY[i::text, 'data', 'status'],
                to_jsonb(p_status)
            );
        END IF;
    END LOOP;

    -- Update the message
    UPDATE messages SET content_parts = parts WHERE id = p_message_id;
END;
$$;

ALTER FUNCTION "public"."update_action_status"("p_message_id" "uuid", "p_action_id" "text", "p_status" "text") OWNER TO "postgres";

COMMENT ON FUNCTION "public"."update_action_status"("p_message_id" "uuid", "p_action_id" "text", "p_status" "text") IS 'Updates the status field of an action within content_parts JSONB. Used to mark actions as executed.';

-- ==========================================================
-- TABLES
-- ==========================================================

-- conversations
CREATE TABLE IF NOT EXISTS "public"."conversations" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "title" "text" DEFAULT 'New Conversation'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."conversations" OWNER TO "postgres";

-- messages
CREATE TABLE IF NOT EXISTS "public"."messages" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "conversation_id" "uuid" NOT NULL,
    "role" "text" NOT NULL,
    "content" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "content_parts" "jsonb",
    "input_type" "text" DEFAULT 'text'::"text",
    CONSTRAINT "messages_input_type_check" CHECK (("input_type" = ANY (ARRAY['text'::"text", 'voice'::"text"]))),
    CONSTRAINT "messages_role_check" CHECK (("role" = ANY (ARRAY['user'::"text", 'assistant'::"text", 'system'::"text", 'tool'::"text"])))
);

ALTER TABLE "public"."messages" OWNER TO "postgres";

COMMENT ON TABLE "public"."messages" IS 'Chat messages. content_parts is the source of truth for structured content (text, display, action, sources parts).';

COMMENT ON COLUMN "public"."messages"."content_parts" IS 'Array of content parts. Types: text, source_ref, action, display, sources. Preserves interleaving order from streaming.';

COMMENT ON COLUMN "public"."messages"."input_type" IS 'How the message was input: text (typed) or voice (spoken via voice mode)';

-- chat_attachments
CREATE TABLE IF NOT EXISTS "public"."chat_attachments" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "conversation_id" "uuid" NOT NULL,
    "message_id" "uuid",
    "filename" "text" NOT NULL,
    "mime_type" "text" NOT NULL,
    "file_size" bigint NOT NULL,
    "width" integer,
    "height" integer,
    "r2_key" "text" NOT NULL,
    "thumbnail_r2_key" "text",
    "status" "text" DEFAULT 'uploading'::"text" NOT NULL,
    "source" "text" DEFAULT 'user'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "chat_attachments_source_check" CHECK (("source" = ANY (ARRAY['user'::"text", 'assistant'::"text"]))),
    CONSTRAINT "chat_attachments_status_check" CHECK (("status" = ANY (ARRAY['uploading'::"text", 'uploaded'::"text", 'error'::"text"])))
);

ALTER TABLE "public"."chat_attachments" OWNER TO "postgres";

COMMENT ON TABLE "public"."chat_attachments" IS 'Stores metadata for images/files attached to chat messages. Files stored in R2 at chat-attachments/{user_id}/{conversation_id}/{uuid}.{ext}';

COMMENT ON COLUMN "public"."chat_attachments"."message_id" IS 'NULL until message is sent, then linked to the message';

COMMENT ON COLUMN "public"."chat_attachments"."status" IS 'uploading: presigned URL issued, uploaded: confirmed in R2, error: upload failed';

COMMENT ON COLUMN "public"."chat_attachments"."source" IS 'user: uploaded by user, assistant: generated by AI (future)';

-- ==========================================================
-- PRIMARY KEYS
-- ==========================================================

ALTER TABLE ONLY "public"."conversations"
    ADD CONSTRAINT "conversations_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."chat_attachments"
    ADD CONSTRAINT "chat_attachments_pkey" PRIMARY KEY ("id");

-- ==========================================================
-- FOREIGN KEYS
-- ==========================================================

ALTER TABLE ONLY "public"."conversations"
    ADD CONSTRAINT "conversations_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."chat_attachments"
    ADD CONSTRAINT "chat_attachments_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."chat_attachments"
    ADD CONSTRAINT "chat_attachments_message_id_fkey" FOREIGN KEY ("message_id") REFERENCES "public"."messages"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."chat_attachments"
    ADD CONSTRAINT "chat_attachments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

-- ==========================================================
-- INDEXES
-- ==========================================================

CREATE INDEX "idx_conversations_updated_at" ON "public"."conversations" USING "btree" ("updated_at" DESC);

CREATE INDEX "idx_conversations_user_id" ON "public"."conversations" USING "btree" ("user_id");

CREATE INDEX "idx_chat_attachments_conversation_id" ON "public"."chat_attachments" USING "btree" ("conversation_id");

CREATE INDEX "idx_chat_attachments_message_id" ON "public"."chat_attachments" USING "btree" ("message_id");

CREATE UNIQUE INDEX "idx_chat_attachments_r2_key" ON "public"."chat_attachments" USING "btree" ("r2_key");

CREATE INDEX "idx_chat_attachments_status" ON "public"."chat_attachments" USING "btree" ("status") WHERE ("status" = 'uploading'::"text");

CREATE INDEX "idx_chat_attachments_user_id" ON "public"."chat_attachments" USING "btree" ("user_id");

CREATE INDEX "idx_messages_content_parts" ON "public"."messages" USING "gin" ("content_parts");
CREATE INDEX "idx_messages_conversation_id" ON "public"."messages" USING "btree" ("conversation_id");
CREATE INDEX "idx_messages_input_type" ON "public"."messages" USING "btree" ("input_type");

-- ==========================================================
-- ROW LEVEL SECURITY
-- ==========================================================

ALTER TABLE "public"."conversations" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."messages" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."chat_attachments" ENABLE ROW LEVEL SECURITY;

-- ==========================================================
-- POLICIES: conversations
-- ==========================================================

CREATE POLICY "Users can insert their own conversations" ON "public"."conversations" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));

CREATE POLICY "Users can view their own conversations" ON "public"."conversations" FOR SELECT USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));

CREATE POLICY "Users can update their own conversations" ON "public"."conversations" FOR UPDATE USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));

CREATE POLICY "Users can delete their own conversations" ON "public"."conversations" FOR DELETE USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));

-- ==========================================================
-- POLICIES: messages
-- ==========================================================

CREATE POLICY "Users can insert messages to their conversations" ON "public"."messages" FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."conversations"
  WHERE (("conversations"."id" = "messages"."conversation_id") AND ("conversations"."user_id" = ( SELECT "auth"."uid"() AS "uid"))))));

CREATE POLICY "Users can view messages of their conversations" ON "public"."messages" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM "public"."conversations"
  WHERE (("conversations"."id" = "messages"."conversation_id") AND ("conversations"."user_id" = ( SELECT "auth"."uid"() AS "uid"))))));

-- ==========================================================
-- POLICIES: chat_attachments
-- ==========================================================

CREATE POLICY "Users can insert their own attachments" ON "public"."chat_attachments" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can view their own attachments" ON "public"."chat_attachments" FOR SELECT USING (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can update their own attachments" ON "public"."chat_attachments" FOR UPDATE USING (("auth"."uid"() = "user_id"));

CREATE POLICY "Users can delete their own attachments" ON "public"."chat_attachments" FOR DELETE USING (("auth"."uid"() = "user_id"));

-- ==========================================================
-- TRIGGERS
-- ==========================================================

CREATE OR REPLACE TRIGGER "update_conversations_updated_at" BEFORE UPDATE ON "public"."conversations" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();

-- ==========================================================
-- GRANTS: functions
-- ==========================================================

GRANT ALL ON FUNCTION "public"."update_action_status"("p_message_id" "uuid", "p_action_id" "text", "p_status" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."update_action_status"("p_message_id" "uuid", "p_action_id" "text", "p_status" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_action_status"("p_message_id" "uuid", "p_action_id" "text", "p_status" "text") TO "service_role";

-- ==========================================================
-- GRANTS: tables
-- ==========================================================

GRANT ALL ON TABLE "public"."conversations" TO "anon";
GRANT ALL ON TABLE "public"."conversations" TO "authenticated";
GRANT ALL ON TABLE "public"."conversations" TO "service_role";

GRANT ALL ON TABLE "public"."messages" TO "anon";
GRANT ALL ON TABLE "public"."messages" TO "authenticated";
GRANT ALL ON TABLE "public"."messages" TO "service_role";

GRANT ALL ON TABLE "public"."chat_attachments" TO "anon";
GRANT ALL ON TABLE "public"."chat_attachments" TO "authenticated";
GRANT ALL ON TABLE "public"."chat_attachments" TO "service_role";
